// Generated by gencpp from file me416_lab/MotorSpeeds.msg
// DO NOT EDIT!


#ifndef ME416_LAB_MESSAGE_MOTORSPEEDS_H
#define ME416_LAB_MESSAGE_MOTORSPEEDS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace me416_lab
{
template <class ContainerAllocator>
struct MotorSpeeds_
{
  typedef MotorSpeeds_<ContainerAllocator> Type;

  MotorSpeeds_()
    : left(0.0)
    , right(0.0)  {
    }
  MotorSpeeds_(const ContainerAllocator& _alloc)
    : left(0.0)
    , right(0.0)  {
  (void)_alloc;
    }



   typedef double _left_type;
  _left_type left;

   typedef double _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::me416_lab::MotorSpeeds_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::me416_lab::MotorSpeeds_<ContainerAllocator> const> ConstPtr;

}; // struct MotorSpeeds_

typedef ::me416_lab::MotorSpeeds_<std::allocator<void> > MotorSpeeds;

typedef boost::shared_ptr< ::me416_lab::MotorSpeeds > MotorSpeedsPtr;
typedef boost::shared_ptr< ::me416_lab::MotorSpeeds const> MotorSpeedsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::me416_lab::MotorSpeeds_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::me416_lab::MotorSpeeds_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace me416_lab

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'me416_lab': ['/home/kpdudek/ros_ws/src/me416_lab/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::me416_lab::MotorSpeeds_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::me416_lab::MotorSpeeds_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::me416_lab::MotorSpeeds_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::me416_lab::MotorSpeeds_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::me416_lab::MotorSpeeds_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::me416_lab::MotorSpeeds_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::me416_lab::MotorSpeeds_<ContainerAllocator> >
{
  static const char* value()
  {
    return "50c2436c38cded221d061b57126c4e40";
  }

  static const char* value(const ::me416_lab::MotorSpeeds_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x50c2436c38cded22ULL;
  static const uint64_t static_value2 = 0x1d061b57126c4e40ULL;
};

template<class ContainerAllocator>
struct DataType< ::me416_lab::MotorSpeeds_<ContainerAllocator> >
{
  static const char* value()
  {
    return "me416_lab/MotorSpeeds";
  }

  static const char* value(const ::me416_lab::MotorSpeeds_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::me416_lab::MotorSpeeds_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 left\n"
"float64 right\n"
;
  }

  static const char* value(const ::me416_lab::MotorSpeeds_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::me416_lab::MotorSpeeds_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorSpeeds_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::me416_lab::MotorSpeeds_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::me416_lab::MotorSpeeds_<ContainerAllocator>& v)
  {
    s << indent << "left: ";
    Printer<double>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<double>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ME416_LAB_MESSAGE_MOTORSPEEDS_H
