// Generated by gencpp from file me416_lab/MotorSpeedsStamped.msg
// DO NOT EDIT!


#ifndef ME416_LAB_MESSAGE_MOTORSPEEDSSTAMPED_H
#define ME416_LAB_MESSAGE_MOTORSPEEDSSTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace me416_lab
{
template <class ContainerAllocator>
struct MotorSpeedsStamped_
{
  typedef MotorSpeedsStamped_<ContainerAllocator> Type;

  MotorSpeedsStamped_()
    : header()
    , left(0.0)
    , right(0.0)  {
    }
  MotorSpeedsStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left(0.0)
    , right(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _left_type;
  _left_type left;

   typedef double _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::me416_lab::MotorSpeedsStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::me416_lab::MotorSpeedsStamped_<ContainerAllocator> const> ConstPtr;

}; // struct MotorSpeedsStamped_

typedef ::me416_lab::MotorSpeedsStamped_<std::allocator<void> > MotorSpeedsStamped;

typedef boost::shared_ptr< ::me416_lab::MotorSpeedsStamped > MotorSpeedsStampedPtr;
typedef boost::shared_ptr< ::me416_lab::MotorSpeedsStamped const> MotorSpeedsStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::me416_lab::MotorSpeedsStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::me416_lab::MotorSpeedsStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace me416_lab

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'me416_lab': ['/home/kpdudek/ros_ws/src/me416_lab/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::me416_lab::MotorSpeedsStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::me416_lab::MotorSpeedsStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::me416_lab::MotorSpeedsStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::me416_lab::MotorSpeedsStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::me416_lab::MotorSpeedsStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::me416_lab::MotorSpeedsStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::me416_lab::MotorSpeedsStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f32685125452f5bdf68130369af5296";
  }

  static const char* value(const ::me416_lab::MotorSpeedsStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f32685125452f5bULL;
  static const uint64_t static_value2 = 0xdf68130369af5296ULL;
};

template<class ContainerAllocator>
struct DataType< ::me416_lab::MotorSpeedsStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "me416_lab/MotorSpeedsStamped";
  }

  static const char* value(const ::me416_lab::MotorSpeedsStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::me416_lab::MotorSpeedsStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 left\n"
"float64 right\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::me416_lab::MotorSpeedsStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::me416_lab::MotorSpeedsStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorSpeedsStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::me416_lab::MotorSpeedsStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::me416_lab::MotorSpeedsStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left: ";
    Printer<double>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<double>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ME416_LAB_MESSAGE_MOTORSPEEDSSTAMPED_H
